// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type Courier struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Price         int    `json:"price"`
	EstimatedTime int    `json:"estimatedTime"`
}

type NewAddress struct {
	Location   string `json:"location"`
	City       string `json:"city"`
	Phone      string `json:"phone"`
	PostalCode int    `json:"postalCode"`
	User       string `json:"user"`
	Title      string `json:"title"`
	IsPrimary  bool   `json:"isPrimary"`
}

type NewCart struct {
	Qty     int    `json:"qty"`
	Product string `json:"product"`
	User    string `json:"user"`
}

type NewCategory struct {
	Name string `json:"name"`
}

type NewCourier struct {
	Name          string `json:"name"`
	Price         int    `json:"price"`
	EstimatedTime int    `json:"estimatedTime"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Images      *string `json:"images"`
	Description string  `json:"description"`
	Price       int     `json:"price"`
	Discount    float64 `json:"discount"`
	Stock       int     `json:"stock"`
	Metadata    string  `json:"metadata"`
	Category    string  `json:"category"`
}

type NewProductImage struct {
	Image   string `json:"image"`
	Product string `json:"product"`
}

type NewReview struct {
	Score       int    `json:"score"`
	Description string `json:"description"`
	Image       string `json:"image"`
	Anonymous   bool   `json:"anonymous"`
	Product     string `json:"product"`
}

type NewShop struct {
	Name     string `json:"name"`
	NameSlug string `json:"nameSlug"`
	Address  string `json:"address"`
	User     string `json:"user"`
	Phone    string `json:"phone"`
}

type NewTransaction struct {
	User    string `json:"user"`
	Address string `json:"address"`
	Courier string `json:"courier"`
	Voucher string `json:"voucher"`
}

type NewTransactionDetail struct {
	Transaction string `json:"transaction"`
	Product     string `json:"product"`
	Qty         int    `json:"qty"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type NewVoucher struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Discount    float64   `json:"discount"`
	Tnc         string    `json:"tnc"`
	StartTime   time.Time `json:"startTime"`
	EndTime     time.Time `json:"endTime"`
	Shop        *string   `json:"shop"`
	IsGlobal    bool      `json:"isGlobal"`
}

type NewWishlist struct {
	Product string `json:"product"`
	User    string `json:"user"`
}

type ProductFilter struct {
	Name         *string   `json:"name"`
	Category     *string   `json:"category"`
	MinPrice     *int      `json:"minPrice"`
	MaxPrice     *int      `json:"maxPrice"`
	Store        []*string `json:"store"`
	Location     []*string `json:"location"`
	Shipping     []*string `json:"shipping"`
	Rating       []*int    `json:"rating"`
	ShippingTime []*string `json:"shippingTime"`
	ProductAdded []*int    `json:"productAdded"`
}

type RedeemVoucher struct {
	User    string `json:"user"`
	Voucher string `json:"voucher"`
}

type UpdateAddress struct {
	Location   string `json:"location"`
	City       string `json:"city"`
	Phone      string `json:"phone"`
	PostalCode int    `json:"postalCode"`
	Title      string `json:"title"`
	IsPrimary  bool   `json:"isPrimary"`
}

type UpdateBalance struct {
	Balance int `json:"balance"`
}

type UpdateBlockStatus struct {
	IsBlocked bool `json:"isBlocked"`
}

type UpdateCart struct {
	Qty int `json:"qty"`
}

type UpdateProduct struct {
	Name        string  `json:"name"`
	Images      *string `json:"images"`
	Description string  `json:"description"`
	Price       int     `json:"price"`
	Discount    float64 `json:"discount"`
	Stock       int     `json:"stock"`
	Metadata    string  `json:"metadata"`
	Category    string  `json:"category"`
}

type UpdateShop struct {
	Name        string    `json:"name"`
	NameSlug    string    `json:"nameSlug"`
	Profile     string    `json:"profile"`
	Slogan      string    `json:"slogan"`
	Description string    `json:"description"`
	OpenHour    time.Time `json:"openHour"`
	CloseHour   time.Time `json:"closeHour"`
	IsOpen      bool      `json:"isOpen"`
}

type UpdateUser struct {
	Email   string `json:"email"`
	Picture string `json:"picture"`
	Name    string `json:"name"`
	Dob     string `json:"dob"`
	Gender  string `json:"gender"`
	Phone   string `json:"phone"`
}
